version: "3"

services:

  gaming-backend:
    build:
      context: ./onfon-gaming-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env