version: "3.8"
services:
  epicgames_server:
    build:
      context: .
      dockerfile: Dockerfile  # Adjust the Dockerfile name if needed
    env_file:
      - .env
    container_name: epicgames_server
    ports:
      - "8080:8080"
    tty: true
    restart: "no"
    networks:
      - epicgames_server_network

networks:
  epicgames_server_network:
    driver: bridge
